INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (18, 6169000, 'iPhone 11 Pro Max 256 GB verde101.png', 'iPhone 11 Pro Max 256 GB verde', 6, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (21, 7499900, 'Celular SAMSUNG Galaxy FOLD 512GB Plateado837.png', 'Celular SAMSUNG Galaxy FOLD 512GB Plateado', 6, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (24, 14999000, 'ROG Strix SCAR 17 - Intel Core i9 - 16GB RAM - Disco Estado Sólido 1TB551.png', 'ROG Strix SCAR 17 - Intel Core i9 - 16GB RAM - Disco Estado Sólido 1TB', 6, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (26, 210000, 'Camisa Blanca Diesel205.png', 'Camisa Blanca Diesel', 2, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (27, 210000, 'Pantalon Americanino585.png', 'Pantalon Americanino', 2, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (28, 209900, 'Buso Americanino - Negro511.png', 'Buso Americanino - Negro', 2, 15, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (29, 229000, 'Chaqueta Americanino - Negro319.png', 'Chaqueta Americanino - Negro', 2, 30, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (30, 290000, 'Chaqueta Americanino - Amarilla317.png', 'Chaqueta Americanino - Amarilla', 2, 10, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (31, 349000, 'Conjunto Buso - Love929.png', 'Conjunto Buso - Love', 4, 5, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (32, 129000, 'Vestido Color Rosa - Mujer729.png', 'Vestido Color Rosa - Mujer', 3, 5, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (33, 120000, 'Blusa Color Rojo35.png', 'Blusa Color Rojo', 3, 50, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (34, 304900, 'Chaqueta Color Negro695.png', 'Chaqueta Color Negro', 4, 25, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (36, 1490000, 'Escobar FOLD615.png', 'Escobar FOLD', 6, 90, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (37, 2900000, 'Play Station 5 + Control + 1TB817.png', 'Play Station 5 + Control + 1TB', 6, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (38, 2600000, 'Xbox Series X504.png', 'Xbox Series X', 6, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (39, 180000, 'Blusa Suelta con Manga381.png', 'Blusa Suelta con Manga', 3, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (40, 1999000, 'Reloj Diesel Hombre Dz7395 Original Mr Daddy 2.0155.png', 'Reloj Diesel Hombre Dz7395 Original Mr Daddy 2.0', 2, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (41, 90000, 'Blusa Para Verano622.png', 'Blusa Para Verano', 4, 0, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (43, 500000, 'Vestido Plateado439.png', 'Vestido Plateado', 4, 20, '369Garantia.jpg');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (44, 369000, 'Bolso negro323.png', 'Bolso negro', 3, 10, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (45, 260000, 'Camisa Hombre Hym510.png', 'Camisa Hombre Hym', 3, 10, '');
INSERT INTO tienda.productos (id, price, imagen, name, id_categoria, oferta, descargable) VALUES (46, 110000, 'Blusa gris845.png', 'Blusa gris', 3, 0, '');